# Generated by Django 4.1.7 on 2023-03-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0009_usercategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
